services:
  endpoint:
    image: ragend
    build: ./server-app
    command: bash -c "cd /home/endpoint && source ./endp_env/bin/activate && gunicorn -w 4 -b 127.0.0.1:5000 run:app" # replace "gunicorn -w 4 -b 127.0.0.1:5000 run:app" with "python run.py" tp run dev server
    env_file: ./server-app/.env
    network_mode: host
    depends_on: 
      - mariadb

  mariadb:
    image: mariadb
    env_file: ./server-app/.env
    network_mode: host
    ports:
      - "3306:3306"
    volumes:
      - "./init.sql:/docker-entrypoint-initdb.d/1.sql"

  client:
    image: nmpimage
    build: ./react-app
    command: sh -c "cd /home/react-app && npm start"
    ports:
      - "3000:3000"
    depends_on:
      - endpoint
